# Generated by Django 5.2.8 on 2025-11-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climate",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
