# Generated by Django 5.2.8 on 2025-11-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0002_alter_climate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planet",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="terrain",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
