# Generated by Django 5.2.8 on 2025-11-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0003_alter_planet_name_alter_terrain_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planet",
            name="population",
            field=models.PositiveBigIntegerField(null=True, verbose_name="Population"),
        ),
    ]
